name: Generate GitHub Stats
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Language Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: danmaciel
          filename: languages.svg
          template: classic
          base: ""

          plugin_languages: yes
          plugin_languages_ignored: html, css, makefile, shell
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes # Analisa o hist√≥rico de commits
          plugin_languages_limit: 8
          
          config_timezone: America/Sao_Paulo
