name: Generate GitHub Stats
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Languages Only
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: danmaciel
          filename: languages.svg
          base: "" # Remove tudo (foto, nome, etc)
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_indepth: yes # Crucial para ler o c√≥digo
