name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza a cada 12 horas
  workflow_dispatch: # Permite rodar manualmente

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Stats Images
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: danmaciel
          template: classic
          filename: github-metrics.svg
          base: header, metadata
          plugin_languages: yes
          plugin_languages_ignored: html, css, makefile, shell
          plugin_languages_details: percentage, lines # Adicionado 'lines' para mais detalhe
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes # Análise profunda dos repositórios
          plugin_languages_limit: 8
          
          # Estética e Localização
          config_timezone: America/Sao_Paulo
          config_order: base.header, isocalendar, languages # Força a ordem de exibição
