name: Generate GitHub Stats
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: General Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: danmaciel
          filename: github-metrics.svg
          base: header, activity, metadata
          config_timezone: America/Sao_Paulo

      - name: Language Ranking
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: danmaciel
          filename: languages.svg
          base: "" # IMPORTANTE: Vazio para não repetir o cabeçalho
          plugin_languages: yes
          plugin_languages_ignored: html, css, makefile, shell
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
