name: Generate GitHub Stats
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: danmaciel
          template: classic
          base: header, metadata
          filename: github-metrics.svg
          
          # Configurações de Linguagens
          plugin_languages: yes
          plugin_languages_ignored: html, css, makefile, shell
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 1000 # Carrega até 1000 commits recentes
          plugin_languages_sections: most-used
          
          config_timezone: America/Sao_Paulo
          config_order: base.header, languages
